SELECT
    CASE
        WHEN GROUPING(rd.SIGLA_RDIS) = 1 THEN 'COPEL'
        ELSE rd.SIGLA_RDIS
    END AS REGIONAL_TOTAL,
    CASE rd.SIGLA_RDIS
        WHEN 'CSL' THEN 'P'
        WHEN 'NRT' THEN 'L'
        WHEN 'NRO' THEN 'M'
        WHEN 'LES' THEN 'C'
        WHEN 'OES' THEN 'V'
        ELSE 'COPEL'
    END AS SIGLA_REGIONAL,
    TO_CHAR(ANO_MES_HQCL, 'yyyy-mm') AS ANOMES,
    SUM(QTDE_CONS_FAT_URB_HQCL + QTDE_CONS_FAT_RUR_HQCL) AS UC_FATURADA
FROM
    IQS.HIST_QTDE_CONS_LOCAL hqcl
INNER JOIN CIS.LOCALIDADE l ON
    l.COD_LOCAL = hqcl.COD_LOCAL_HQCL
LEFT JOIN CIS.SECCIONAL_DISTRIBUICAO sc ON
    l.COD_SECCION_DISTR_LOCAL = sc.COD_SDIS
LEFT JOIN CIS.REGIONAL_DISTRIBUICAO rd ON
    sc.COD_REG_DISTR_SDIS = rd.COD_RDIS
WHERE
    ANO_MES_HQCL >= TO_DATE(:p_data_ini, 'yyyy-mm-dd')
    AND rd.SIGLA_RDIS <> 'SCD'
GROUP BY
    ROLLUP (rd.SIGLA_RDIS),
    TO_CHAR(ANO_MES_HQCL, 'yyyy-mm')
ORDER BY
    ANOMES DESC,
    REGIONAL_TOTAL ASC
